language: r

r:
  - oldrel
  - release
  - devel

r_packages:
 - BH
 - Rcpp
 - testthat
 - covr
 - roxygen2
 - devtools

before_script:
 - Rscript -e 'devtools::document()'

after_success:
 - Rscript -e 'covr::coveralls()'
 - Rscript -e 'library(covr); codecov()'